//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhipoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KhipoEntities : DbContext
    {
        public KhipoEntities()
            : base("name=KhipoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Produto> Produto { get; set; }
    
        public virtual ObjectResult<GetAllProduto_Result> GetAllProduto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProduto_Result>("GetAllProduto");
        }
    
        public virtual ObjectResult<GetProdutoById_Result> GetProdutoById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProdutoById_Result>("GetProdutoById", idParameter);
        }
    }
}
